services:
  - type: web
    name: fastapi-backend
    env: python
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python -m uvicorn main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: your-database-name
          property: connectionString
      - key: SECRET_KEY
        value: your_secret_key_here
      # Add more env vars here as needed
    healthCheckPath: /
    autoDeploy: true
