services:
  - type: web
    name: fastapi-backend
    env: python
    branch: main
    buildCommand: cd fastapi && pip install -r requirements.txt
    startCommand: cd fastapi && python -m uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: your-database-name
          property: connectionString
      - key: SECRET_KEY
        value: your_secret_key_here
    healthCheckPath: /
    autoDeploy: true
